services:
  klipper:
    privileged: true
    build:
      context: ./klipper
      dockerfile: Dockerfile
    image: klipper-mawi
    container_name: klipper
    cap_add:
      - SYS_NICE
    group_add:
      - dialout
    restart: unless-stopped
    ports:
      - 7125:7125
    volumes:
      - gcode_files:/home/klippy/gcode_files
      - moonraker_data:/home/klippy/.moonraker_database
      - /dev/serial:/dev/serial
      - klippy_uds:/tmp
      - ./printer_data:/home/klippy/printer_data
      - ./klipper/scripts/supervisord.conf:/etc/supervisord.conf
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - traefik_default
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    entrypoint: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]


  mainsail:
    image: dimalo/mainsail
    container_name: mainsail
    restart: unless-stopped
    volumes:
      - ./printer_data:/home/pi/printer_data
      - klippy_uds:/tmp
    networks:
      - traefik_default
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.mainsail.rule=Host(`kobra.lan`)"
      - "traefik.http.routers.mainsail.entrypoints=web"
      - "traefik.http.services.mainsail.loadbalancer.server.port=80"

volumes:
  gcode_files:
  moonraker_data:
  klippy_uds:

networks:
  traefik_default:
    external: true

